# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: //puma.student.lth.se/mi3105is-s/Downloads/vga_constraints.xdc

# Block Designs: bd/ForegroundBRAM/ForegroundBRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ForegroundBRAM || ORIG_REF_NAME==ForegroundBRAM}]

# IP: bd/ForegroundBRAM/ip/ForegroundBRAM_blk_mem_gen_0_0/ForegroundBRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ForegroundBRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==ForegroundBRAM_blk_mem_gen_0_0}]

# Block Designs: bd/clk/clk.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk || ORIG_REF_NAME==clk}]

# IP: bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_clk_wiz_0_1 || ORIG_REF_NAME==clk_clk_wiz_0_1}]

# XDC: bd/ForegroundBRAM/ip/ForegroundBRAM_blk_mem_gen_0_0/ForegroundBRAM_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/ForegroundBRAM/ForegroundBRAM_ooc.xdc

# XDC: bd/clk/clk_ooc.xdc
