# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mi3105is-s/Program/Vga_new_test/project_2/project_2.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1.xci
# IP: The module: 'clk_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mi3105is-s/Program/Vga_new_test/project_2/project_2.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/mi3105is-s/Program/Vga_new_test/project_2/project_2.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/mi3105is-s/Program/Vga_new_test/project_2/project_2.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/mi3105is-s/Program/Vga_new_test/project_2/project_2.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1.xci
# IP: The module: 'clk_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mi3105is-s/Program/Vga_new_test/project_2/project_2.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/mi3105is-s/Program/Vga_new_test/project_2/project_2.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/mi3105is-s/Program/Vga_new_test/project_2/project_2.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_1/clk_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
